name: Build and Deploy Documentation

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "pycalf/**"
      - ".github/workflows/docs-build.yml"
  pull_request:
    branches: [main]
    paths:
      - "docs/**"
      - "pycalf/**"
  # 手動実行も可能に
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# GitHub Pagesのために一度に1つのデプロイのみを許可
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          pip install uv

      - name: Install dependencies with uv
        run: |
          uv venv
          uv pip install -e .
          uv pip install sphinx sphinx_rtd_theme

      - name: Build documentation
        working-directory: docs
        run: |
          make html
          # GitHub Pagesのルートディレクトリを作成
          mkdir -p _site
          cp -r _build/html/* _site/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/_site"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    # mainブランチへのプッシュの場合のみデプロイ
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
