name: Publish Python Package

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pycalf
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Sync environment with uv
        run: uv sync

      - name: Generate dynamic version from commit hash for TestPyPI
        if: github.ref == 'refs/heads/main'
        run: |
          COMMIT_HASH=$(echo "${GITHUB_SHA}" | cut -c1-7)
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          # PEP 440に準拠したバージョン形式に修正
          NEW_VERSION="0.0.1.dev${TIMESTAMP}+${COMMIT_HASH}"
          echo "Generated version for TestPyPI: ${NEW_VERSION}"
          sed -i "s/^version\s*=.*/version = \"${NEW_VERSION}\"/" pyproject.toml

      - name: Build the package with uv
        run: uv build

      - name: Show package files
        run: ls -la dist/

      - name: Publish to TestPyPI
        id: publish-testpypi
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          verbose: true

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v') && steps.publish-testpypi.outcome == 'success'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
