name: Publish Python Package

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pycalf
    permissions:
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Sync environment with uv
        run: uv sync

      - name: Extract version from tag
        if: startsWith(github.ref, 'refs/tags/v')
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Generate dynamic version for TestPyPI (main branch, no tag)
        if: github.ref == 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/v')
        run: |
          NEW_VERSION="0.3.1.dev${GITHUB_RUN_NUMBER}"
          echo "Generated version for TestPyPI: ${NEW_VERSION}"
          sed -i "s/^version\s*=.*/version = \"${NEW_VERSION}\"/" pyproject.toml

      - name: Set version from tag (when tag is present)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          TAG_VERSION="${{ steps.get_version.outputs.VERSION }}"
          echo "Using version from tag: ${TAG_VERSION}"
          sed -i "s/^version\s*=.*/version = \"${TAG_VERSION}\"/" pyproject.toml

      - name: Build the package with uv
        run: uv build

      - name: Publish to TestPyPI
        id: publish-testpypi
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish to PyPI
        if: steps.publish-testpypi.outcome == 'success'
        uses: pypa/gh-action-pypi-publish@release/v1
