name: Publish Python Package

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pycalf
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Sync environment with uv
        run: uv sync

      - name: Generate dynamic version for TestPyPI (main branch)
        if: github.ref == 'refs/heads/main'
        run: |
          NEW_VERSION="0.0.1.dev${GITHUB_RUN_NUMBER}"
          echo "Generated version for TestPyPI: ${NEW_VERSION}"
          sed -i "s/^version\s*=.*/version = \"${NEW_VERSION}\"/" pyproject.toml

      - name: Build the package with uv
        run: uv build

      - name: Publish to TestPyPI
        if: github.ref == 'refs/heads/main'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}

      # PyPI への公開（タグプッシュの場合）
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
