name: Publish Python Package

on:
  push:
    branches: [main, release/*]
    tags: ["v*"]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pycalf
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel

      - name: Set version
        id: set_version
        run: |
          if [[ $GITHUB_REF == refs/tags/v* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "Using tag version: ${VERSION}"
          else
            VERSION="0.0.1.dev${GITHUB_RUN_NUMBER}"
            echo "Using development version: ${VERSION}"
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          sed -i "s/^version\s*=.*/version = \"${VERSION}\"/" pyproject.toml

      - name: Build package
        run: python -m build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
